'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { dispatchEntity, founderOsMock, operatingLoop, type EntityRecord } from '@/lib/founderOs';

type Headquarters = { totals: { companies: number; departments: number; agents: number; tasks: number; approvals: number }; companies: Array<{ id: number; name: string; approvals: Array<{ id: number; company_id: number; title: string; summary?: string; status: string; risk_level: string; approval_type?: string }> }> };
type Blueprint = { archetype: string; company: { name: string; description: string }; departments: Array<{ teams: Array<{ agents: unknown[] }> }>; tasks: unknown[]; approvals: unknown[]; connectors: unknown[]; estimatedMonthlyCost: number };

export default function CommandCenterPage() {
  const [headquarters, setHeadquarters] = useState<Headquarters | null>(null);
  const [objective, setObjective] = useState('Build an AI media company for practical small-business technology education.');
  const [blueprint, setBlueprint] = useState<Blueprint | null>(null);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');

  const refresh = () => fetch('/api/headquarters').then((response) => response.json()).then(setHeadquarters).catch(() => undefined);
  useEffect(() => { void refresh(); }, []);

  const apiApprovals = useMemo(() => headquarters?.companies.flatMap((company) => company.approvals.filter((approval) => approval.status === 'pending').map<EntityRecord>((approval) => ({ id: String(approval.id), kind: 'approval', name: approval.title, status: approval.status, summary: approval.summary || 'Founder decision required before execution.', company: company.name, risk: (approval.risk_level as EntityRecord['risk']) || 'medium', traceId: `CYV-${approval.id}` }))) || [], [headquarters]);
  const approvals = apiApprovals.length ? apiApprovals : founderOsMock.approvals;

  async function previewMission() {
    if (!objective.trim()) return;
    setLoading(true); setMessage(''); setBlueprint(null);
    try {
      const response = await fetch('/api/executive-ai/blueprint', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ objective }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || 'Unable to generate blueprint.');
      setBlueprint(data.blueprint);
      setMessage('Research package and blueprint are ready for founder review.');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to generate blueprint.'); }
    finally { setLoading(false); }
  }

  return <main className="mx-auto max-w-[1500px] px-4 py-6 md:px-7 md:py-8">
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-[0_20px_60px_rgba(15,23,42,.05)] md:p-8">
        <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-violet-600">Founder triage</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.045em] text-slate-950 md:text-5xl">What requires your authority?</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-600">Cyvora keeps routine execution quiet. This surface shows only decisions, exceptions, active missions, and material changes.</p></div><Link href="/briefing" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 shadow-sm">Open executive briefing</Link></div>
        <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pending decisions" value={approvals.length} tone="amber" /><Metric label="Open incidents" value={founderOsMock.incidents.length} tone="rose" /><Metric label="Active runs" value={founderOsMock.runs.length} tone="blue" /><Metric label="Companies" value={headquarters?.totals.companies ?? founderOsMock.companies.length} tone="slate" /></div>
      </div>

      <div className="rounded-[28px] border border-slate-200 bg-slate-950 p-6 text-white shadow-[0_20px_60px_rgba(15,23,42,.10)] md:p-8"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-cyan-300">Current operating loop</p><div className="mt-5 grid grid-cols-3 gap-2">{operatingLoop.map((step, index) => <div key={step} className={`rounded-xl border p-3 ${index === 1 ? 'border-violet-400/40 bg-violet-400/10' : 'border-white/10 bg-white/[.035]'}`}><span className="font-mono text-[9px] text-slate-500">{String(index + 1).padStart(2, '0')}</span><strong className="mt-4 block text-[11px] font-medium text-slate-200">{step}</strong></div>)}</div></div>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
      <article className="rounded-[28px] border border-slate-200 bg-white p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-amber-600">Action Center</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em] text-slate-950">Founder decisions</h2></div><Link href="/approvals" className="text-xs font-semibold text-slate-500">View all →</Link></div><div className="mt-5 space-y-3">{approvals.map((approval) => <button key={approval.id} onClick={() => dispatchEntity(approval)} className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-left transition hover:border-slate-300 hover:bg-slate-50"><div className="flex items-start justify-between gap-4"><div><strong className="text-sm text-slate-950">{approval.name}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{approval.summary}</p></div><span className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 font-mono text-[9px] uppercase text-amber-700">{approval.risk || 'medium'}</span></div><div className="mt-3 flex gap-4 font-mono text-[9px] text-slate-400"><span>{approval.company}</span><span>{approval.traceId}</span>{typeof approval.cost === 'number' ? <span>${approval.cost.toFixed(2)}</span> : null}</div></button>)}</div></article>

      <article className="rounded-[28px] border border-rose-200 bg-rose-50/60 p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-rose-600">Exception posture</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em] text-slate-950">Incidents and blocks</h2></div><Link href="/war-room" className="text-xs font-semibold text-rose-700">Open War Room →</Link></div><div className="mt-5 space-y-3">{founderOsMock.incidents.map((incident) => <button key={incident.id} onClick={() => dispatchEntity(incident)} className="w-full rounded-2xl border border-rose-200 bg-white p-4 text-left"><div className="flex items-start justify-between gap-4"><div><strong className="text-sm text-slate-950">{incident.name}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{incident.summary}</p></div><span className="rounded-full bg-rose-100 px-2.5 py-1 font-mono text-[9px] uppercase text-rose-700">open</span></div></button>)}</div></article>
    </section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr]">
      <article className="rounded-[28px] border border-slate-200 bg-white p-6 md:p-7"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-violet-600">Mission composer</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em] text-slate-950">State the outcome once.</h2><p className="mt-2 text-sm leading-6 text-slate-500">Research precedes blueprint generation. Nothing executes until the founder approves the structure and policy posture.</p><textarea value={objective} onChange={(event) => { setObjective(event.target.value); setBlueprint(null); }} rows={5} className="mt-5 w-full resize-y rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-7 text-slate-900 outline-none transition focus:border-violet-400 focus:ring-4 focus:ring-violet-100" /><div className="mt-4 flex flex-wrap gap-2"><button disabled={loading || !objective.trim()} onClick={() => void previewMission()} className="rounded-xl bg-gradient-to-r from-violet-600 to-blue-600 px-4 py-3 text-sm font-semibold text-white shadow-sm disabled:opacity-50">{loading ? 'Researching…' : 'Research opportunity'}</button><Link href="/market-intelligence" className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700">Open intelligence</Link></div>{message ? <p className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-700">{message}</p> : null}{blueprint ? <div className="mt-5 rounded-2xl border border-violet-200 bg-violet-50/50 p-5"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-violet-600">Blueprint ready</p><h3 className="mt-2 text-lg font-semibold text-slate-950">{blueprint.company.name}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{blueprint.company.description}</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Departments" value={blueprint.departments.length} /><Mini label="Tasks" value={blueprint.tasks.length} /><Mini label="Approvals" value={blueprint.approvals.length} /><Mini label="Connectors" value={blueprint.connectors.length} /></div></div> : null}</article>

      <article className="rounded-[28px] border border-slate-200 bg-white p-6 md:p-7"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-blue-600">Live workforce</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em] text-slate-950">Active agents</h2></div><Link href="/agents" className="text-xs font-semibold text-slate-500">Registry →</Link></div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200"><div className="grid grid-cols-[1.2fr_.8fr_.7fr] gap-3 bg-slate-50 px-4 py-3 font-mono text-[9px] uppercase tracking-[.12em] text-slate-400"><span>Agent</span><span>Task</span><span>Status</span></div>{founderOsMock.agents.map((agent) => <button key={agent.id} onClick={() => dispatchEntity(agent)} className="grid w-full grid-cols-[1.2fr_.8fr_.7fr] gap-3 border-t border-slate-200 px-4 py-4 text-left text-xs hover:bg-slate-50"><span><strong className="block text-slate-950">{agent.name}</strong><small className="mt-1 block text-slate-400">{agent.company}</small></span><span className="text-slate-500">{String(agent.metadata?.task || 'Unassigned')}</span><span className="font-mono text-[10px] text-blue-700">{agent.status}</span></button>)}</div></article>
    </section>

    <section className="mt-6 rounded-[28px] border border-slate-200 bg-white p-6 md:p-7"><div className="flex items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-emerald-600">Consequential changes</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.035em] text-slate-950">What changed since your last review</h2></div><Link href="/history" className="text-xs font-semibold text-slate-500">Full history →</Link></div><div className="mt-5 grid gap-3 md:grid-cols-3">{founderOsMock.runs.map((run) => <button key={run.id} onClick={() => dispatchEntity(run)} className="rounded-2xl border border-slate-200 p-4 text-left hover:bg-slate-50"><span className="font-mono text-[9px] uppercase text-slate-400">{run.traceId}</span><strong className="mt-3 block text-sm text-slate-950">{run.name}</strong><p className="mt-2 text-xs leading-5 text-slate-500">{run.summary}</p><span className="mt-4 inline-block rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 font-mono text-[9px] text-slate-600">{run.status}</span></button>)}</div></section>
  </main>;
}

function Metric({ label, value, tone }: { label: string; value: string | number; tone: 'amber' | 'rose' | 'blue' | 'slate' }) { const classes = tone === 'amber' ? 'text-amber-700 bg-amber-50 border-amber-200' : tone === 'rose' ? 'text-rose-700 bg-rose-50 border-rose-200' : tone === 'blue' ? 'text-blue-700 bg-blue-50 border-blue-200' : 'text-slate-700 bg-slate-50 border-slate-200'; return <div className={`rounded-2xl border p-4 ${classes}`}><span className="block text-[10px] uppercase tracking-[.12em] opacity-70">{label}</span><strong className="mt-2 block font-mono text-2xl">{value}</strong></div>; }
function Mini({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-violet-200 bg-white p-3"><span className="block text-[9px] uppercase text-slate-400">{label}</span><strong className="mt-1 block font-mono text-lg text-slate-950">{value}</strong></div>; }
